### ISSUE TITLE
Create personas

### ISSUE THREAD

**Issue by desinole** [desinole/codecampster#2]
Updated per feedback from Brian Hall: The system needs personas. Then the "personas" can have a default set of "roles" (or individual permissions) that get assigned to the user when they get attached with a Persona. The persona could also mean additional things outside of just permissions and authorization.
By default, no role. When user RSVPs, they become attendee. When user adds session to give a speech, they become speaker. Organizer role is something that's assigned by another organizer.

**Comment by Hallmanac** [comment]
Just some a comment here. I actually call these "Personas". Then the "personas" can have a default set of "roles" (or individual permissions) that get assigned to the user when they get attached _with_ a Persona. The persona could also mean additional things outside of just permissions and authorization. Again, just throwing it out there. :-)

**Comment by desinole** [comment]
Personas it is :)
