### ISSUE TITLE
Sessions page has a bad link

### ISSUE THREAD

**Issue by RualStorge** [desinole/codecampster#34]
<img width="1145" alt="screen shot 2017-01-27 at 2 43 54 pm" src="https://cloud.githubusercontent.com/assets/5638847/22385072/3c6e59da-e49f-11e6-924e-a77f0155717d.png">

On http://www.orlandocodecamp.com/Speakers/Sessions the "Learn More" link goes to "http://www.orlandocodecamp.com/Speakers/Details/{id}" when it should go to "http://www.orlandocodecamp.com/Sessions/Details/{id}" (note details link on the far right works, just not the "Learn More" link.)

(I'll try to correct this tonight, but documenting it incase someone else is able to do so first or I'm unable to do so)

**Comment by desinole** [comment]
Thank you. Please let me know if you have any questions

**Comment by TimFerrell** [comment]
This no longer appears to be an issue.
