### ISSUE TITLE
Clicking on speaker website throws error

### ISSUE THREAD

**Issue by slobo80** [desinole/codecampster#38]
I went to http://www.orlandocodecamp.com/speakers/details/35 and clicked on the speaker website link (zdanev.com). I got this error:
![image](https://cloud.githubusercontent.com/assets/1782771/23130833/c8f97948-f73c-11e6-9e25-426aaccaf53d.png)

**Comment by TimFerrell** [comment]
This can be closed now.

**Comment by desinole** [comment]
Thanks for taking care of this
