### ISSUE TITLE
Approve session and assign tracks and times

### ISSUE THREAD

**Issue by desinole** [desinole/codecampster#51]
Ability to set a session as approved and assign it a track and timeslot. Should check for already existing sessions in the same position. Should check for speaker conflicts (same speaker cannot have two sessions at the same time)

**Comment by littlejohnjt** [comment]
Which user's should have the ability to approve sessions and assign tracks and timeslots?

**Comment by desinole** [comment]
admin only

**Comment by littlejohnjt** [comment]
This was completed on 27 Feb 2018.  This functionality still need some CSS applied for better styling.
