### ISSUE TITLE
HTML DOM Issue on Profile Page With Website and Blog Sections

### ISSUE THREAD

**Issue by ericnograles** [desinole/codecampster#56]
Hi there!

See below, it looks like some Razor templates just need some TLC.  The Website link actually cuts over to the Blog, and unfortunately, the Blog link therefore gets nuked on the `/speakers/details` route for an individual speaker

![image](https://user-images.githubusercontent.com/6023705/35070917-033314b4-fbad-11e7-82ec-6bf28820f27c.png)

**Comment by gomjabar6** [comment]
I've fixed this in [my pull request (#57)](/desinole/codecampster/pull/57) along with another bug that isn't manifesting in the live website but is in the source code.

**Comment by desinole** [comment]
Merged. Will test and deploy later today

**Comment by desinole** [comment]
Closing this because fixed
